//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AqarPress.View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of AqarPress.View.DtoClasses.UserView from the entity model.</summary>
	public static partial class UserViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<AqarPress.Data.EntityClasses.UserEntity, AqarPress.View.DtoClasses.UserView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<AqarPress.Data.EntityClasses.UserEntity, AqarPress.View.DtoClasses.UserView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static UserViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to AqarPress.View.DtoClasses.UserView which instances are projected from the 
		/// results of the specified baseQuery, which returns AqarPress.Data.EntityClasses.UserEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve AqarPress.View.DtoClasses.UserView instances</returns>
		public static IQueryable<AqarPress.View.DtoClasses.UserView> ProjectToUserView(this IQueryable<AqarPress.Data.EntityClasses.UserEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to AqarPress.View.DtoClasses.UserView which instances are projected from the
		/// AqarPress.Data.EntityClasses.UserEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>AqarPress.Data.EntityClasses.UserEntity instance created from the specified entity instance</returns>
		public static AqarPress.View.DtoClasses.UserView ProjectToUserView(this AqarPress.Data.EntityClasses.UserEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<AqarPress.Data.EntityClasses.UserEntity, AqarPress.View.DtoClasses.UserView>> CreateProjectionFunc()
		{
			return p__0 => new AqarPress.View.DtoClasses.UserView()
			{
				Id = p__0.Id,
				LastLoginDate = p__0.LastLoginDate,
				MobilePhone = p__0.MobilePhone,
				Name = p__0.Name,
				Password = p__0.Password,
				RoleId = p__0.RoleId,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_UserView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

