//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DB_A4D6F8_AqarPress.Data.HelperClasses
{
	/// <summary>Field Creation Class for entity AreaEntity</summary>
	public partial class AreaFields
	{
		/// <summary>Creates a new AreaEntity.ArabicName field instance</summary>
		public static EntityField2 ArabicName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AreaFieldIndex.ArabicName); }}
		/// <summary>Creates a new AreaEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AreaFieldIndex.Id); }}
		/// <summary>Creates a new AreaEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AreaFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.ArabicName field instance</summary>
		public static EntityField2 ArabicName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.ArabicName); }}
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity DeveloperEntity</summary>
	public partial class DeveloperFields
	{
		/// <summary>Creates a new DeveloperEntity.ArabicName field instance</summary>
		public static EntityField2 ArabicName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DeveloperFieldIndex.ArabicName); }}
		/// <summary>Creates a new DeveloperEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DeveloperFieldIndex.Id); }}
		/// <summary>Creates a new DeveloperEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DeveloperFieldIndex.IsActive); }}
		/// <summary>Creates a new DeveloperEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DeveloperFieldIndex.Name); }}
		/// <summary>Creates a new DeveloperEntity.Path field instance</summary>
		public static EntityField2 Path { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DeveloperFieldIndex.Path); }}
	}

	/// <summary>Field Creation Class for entity ProjectEntity</summary>
	public partial class ProjectFields
	{
		/// <summary>Creates a new ProjectEntity.ArabicName field instance</summary>
		public static EntityField2 ArabicName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.ArabicName); }}
		/// <summary>Creates a new ProjectEntity.CategoryId field instance</summary>
		public static EntityField2 CategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.CategoryId); }}
		/// <summary>Creates a new ProjectEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.DateCreated); }}
		/// <summary>Creates a new ProjectEntity.DeveloperId field instance</summary>
		public static EntityField2 DeveloperId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.DeveloperId); }}
		/// <summary>Creates a new ProjectEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Id); }}
		/// <summary>Creates a new ProjectEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.IsActive); }}
		/// <summary>Creates a new ProjectEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Name); }}
		/// <summary>Creates a new ProjectEntity.Path field instance</summary>
		public static EntityField2 Path { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectFieldIndex.Path); }}
	}

	/// <summary>Field Creation Class for entity ProjectDiscussionEntity</summary>
	public partial class ProjectDiscussionFields
	{
		/// <summary>Creates a new ProjectDiscussionEntity.CommenterId field instance</summary>
		public static EntityField2 CommenterId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectDiscussionFieldIndex.CommenterId); }}
		/// <summary>Creates a new ProjectDiscussionEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectDiscussionFieldIndex.DateCreated); }}
		/// <summary>Creates a new ProjectDiscussionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectDiscussionFieldIndex.Id); }}
		/// <summary>Creates a new ProjectDiscussionEntity.MessageBody field instance</summary>
		public static EntityField2 MessageBody { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectDiscussionFieldIndex.MessageBody); }}
		/// <summary>Creates a new ProjectDiscussionEntity.ProjectId field instance</summary>
		public static EntityField2 ProjectId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectDiscussionFieldIndex.ProjectId); }}
	}

	/// <summary>Field Creation Class for entity ProjectSubCategoryTableEntity</summary>
	public partial class ProjectSubCategoryTableFields
	{
		/// <summary>Creates a new ProjectSubCategoryTableEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectSubCategoryTableFieldIndex.Id); }}
		/// <summary>Creates a new ProjectSubCategoryTableEntity.ProjectId field instance</summary>
		public static EntityField2 ProjectId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectSubCategoryTableFieldIndex.ProjectId); }}
		/// <summary>Creates a new ProjectSubCategoryTableEntity.SubCategoryId field instance</summary>
		public static EntityField2 SubCategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProjectSubCategoryTableFieldIndex.SubCategoryId); }}
	}

	/// <summary>Field Creation Class for entity RoleEntity</summary>
	public partial class RoleFields
	{
		/// <summary>Creates a new RoleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.Id); }}
		/// <summary>Creates a new RoleEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(RoleFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity SubCategoryEntity</summary>
	public partial class SubCategoryFields
	{
		/// <summary>Creates a new SubCategoryEntity.ArabicName field instance</summary>
		public static EntityField2 ArabicName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubCategoryFieldIndex.ArabicName); }}
		/// <summary>Creates a new SubCategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubCategoryFieldIndex.Id); }}
		/// <summary>Creates a new SubCategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubCategoryFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.DateCreated field instance</summary>
		public static EntityField2 DateCreated { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.DateCreated); }}
		/// <summary>Creates a new UserEntity.DeviceToken field instance</summary>
		public static EntityField2 DeviceToken { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.DeviceToken); }}
		/// <summary>Creates a new UserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Id); }}
		/// <summary>Creates a new UserEntity.LastLoginDate field instance</summary>
		public static EntityField2 LastLoginDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.LastLoginDate); }}
		/// <summary>Creates a new UserEntity.MobilePhone field instance</summary>
		public static EntityField2 MobilePhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.MobilePhone); }}
		/// <summary>Creates a new UserEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Name); }}
		/// <summary>Creates a new UserEntity.Password field instance</summary>
		public static EntityField2 Password { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.Password); }}
		/// <summary>Creates a new UserEntity.RoleId field instance</summary>
		public static EntityField2 RoleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UserFieldIndex.RoleId); }}
	}
	

}