//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace AqarPress.Edit.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	[Serializable]
	[DataContract]
	public partial class User
	{
		/// <summary>Gets or sets the DeviceToken field. Derived from Entity Model Field 'User.DeviceToken'</summary>
		[DataMember]
		public System.String DeviceToken { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'User.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the LastLoginDate field. Derived from Entity Model Field 'User.LastLoginDate'</summary>
		[DataMember]
		public Nullable<System.DateTime> LastLoginDate { get; set; }
		/// <summary>Gets or sets the MobilePhone field. Derived from Entity Model Field 'User.MobilePhone'</summary>
		[DataMember]
		public System.String MobilePhone { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'User.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Password field. Derived from Entity Model Field 'User.Password'</summary>
		[DataMember]
		public System.String Password { get; set; }
		/// <summary>Gets or sets the RoleId field. Derived from Entity Model Field 'User.RoleId (FK)'</summary>
		[DataMember]
		public System.Int32 RoleId { get; set; }
	}

}




