//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.ProjectView from the entity model.</summary>
	public static partial class ProjectViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity, View.DtoClasses.ProjectView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity, View.DtoClasses.ProjectView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static ProjectViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.ProjectView which instances are projected from the 
		/// results of the specified baseQuery, which returns DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.ProjectView instances</returns>
		public static IQueryable<View.DtoClasses.ProjectView> ProjectToProjectView(this IQueryable<DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.ProjectView which instances are projected from the
		/// DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.ProjectView ProjectToProjectView(this DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<DB_A4D6F8_AqarPress.Data.EntityClasses.ProjectEntity, View.DtoClasses.ProjectView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.ProjectView()
			{
				ArabicName = p__0.ArabicName,
				CategoryId = p__0.CategoryId,
				DateCreated = p__0.DateCreated,
				DeveloperId = p__0.DeveloperId,
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				Name = p__0.Name,
				Path = p__0.Path,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_ProjectView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

