//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Ad'.</summary>
	[Serializable]
	[DataContract]
	public partial class Ad
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Ad.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Ad.IsActive'</summary>
		[DataMember]
		public Nullable<System.Boolean> IsActive { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Ad.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Path field. Derived from Entity Model Field 'Ad.Path'</summary>
		[DataMember]
		public System.String Path { get; set; }
		/// <summary>Gets or sets the RedirectUrl field. Derived from Entity Model Field 'Ad.RedirectUrl'</summary>
		[DataMember]
		public System.String RedirectUrl { get; set; }
	}

}




