//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Project'.</summary>
	[Serializable]
	[DataContract]
	public partial class ProjectView
	{
		/// <summary>Gets or sets the ArabicName field. Derived from Entity Model Field 'Project.ArabicName'</summary>
		[DataMember]
		public System.String ArabicName { get; set; }
		/// <summary>Gets or sets the CategoryId field. Derived from Entity Model Field 'Project.CategoryId (FK)'</summary>
		[DataMember]
		public System.Int32 CategoryId { get; set; }
		/// <summary>Gets or sets the DateCreated field. Derived from Entity Model Field 'Project.DateCreated'</summary>
		[DataMember]
		public System.DateTime DateCreated { get; set; }
		/// <summary>Gets or sets the DeveloperId field. Derived from Entity Model Field 'Project.DeveloperId (FK)'</summary>
		[DataMember]
		public System.Int32 DeveloperId { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Project.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Project.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Project.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Path field. Derived from Entity Model Field 'Project.Path'</summary>
		[DataMember]
		public System.String Path { get; set; }
	}

}




